Attaching to av-gym-system_celery-beat_1, av-gym-system_celery_1, av-gym-system_frontend_1, av-gym-system_web_1, av-gym-system_db_1, av-gym-system_redis_1
[35mfrontend_1     |[0m /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
[35mfrontend_1     |[0m /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
[35mfrontend_1     |[0m /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
[35mfrontend_1     |[0m 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
[35mfrontend_1     |[0m 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
[35mfrontend_1     |[0m /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
[35mfrontend_1     |[0m /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
[35mfrontend_1     |[0m /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
[35mfrontend_1     |[0m /docker-entrypoint.sh: Configuration complete; ready for start up
[35mfrontend_1     |[0m 127.0.0.1 - - [28/Jul/2025:20:12:50 +0000] "HEAD / HTTP/1.1" 200 0 "-" "Wget/1.25.0"
[35mfrontend_1     |[0m 127.0.0.1 - - [28/Jul/2025:20:13:21 +0000] "HEAD / HTTP/1.1" 200 0 "-" "Wget/1.25.0"
[32mdb_1           |[0m 
[32mdb_1           |[0m PostgreSQL Database directory appears to contain a database; Skipping initialization
[32mdb_1           |[0m 
[32mdb_1           |[0m 2025-07-28 20:12:44.439 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
[32mdb_1           |[0m 2025-07-28 20:12:44.439 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[32mdb_1           |[0m 2025-07-28 20:12:44.440 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[32mdb_1           |[0m 2025-07-28 20:12:44.445 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[32mdb_1           |[0m 2025-07-28 20:12:44.455 UTC [29] LOG:  database system was shut down at 2025-07-28 13:25:22 UTC
[32mdb_1           |[0m 2025-07-28 20:12:44.483 UTC [1] LOG:  database system is ready to accept connections
[34mredis_1        |[0m 1:C 28 Jul 2025 20:12:44.196 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[34mredis_1        |[0m 1:C 28 Jul 2025 20:12:44.197 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[34mredis_1        |[0m 1:C 28 Jul 2025 20:12:44.197 * Redis version=7.4.5, bits=64, commit=00000000, modified=0, pid=1, just started
[34mredis_1        |[0m 1:C 28 Jul 2025 20:12:44.197 * Configuration loaded
[34mredis_1        |[0m 1:M 28 Jul 2025 20:12:44.198 * Increased maximum number of open files to 10032 (it was originally set to 1024).
[34mredis_1        |[0m 1:M 28 Jul 2025 20:12:44.198 * monotonic clock: POSIX clock_gettime
[34mredis_1        |[0m 1:M 28 Jul 2025 20:12:44.201 * Running mode=standalone, port=6379.
[34mredis_1        |[0m 1:M 28 Jul 2025 20:12:44.202 * Server initialized
[34mredis_1        |[0m 1:M 28 Jul 2025 20:12:44.203 * Ready to accept connections tcp
[36mcelery-beat_1  |[0m celery beat v5.3.6 (emerald-rush) is starting.
[36mcelery-beat_1  |[0m ERROR 2025-07-28 20:12:51,162 signal 1 140323695160192 Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f9fa5c0d690>> raised: AttributeError("'tuple' object has no attribute 'append'")
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/bin/celery", line 8, in <module>
[36mcelery-beat_1  |[0m     sys.exit(main())
[36mcelery-beat_1  |[0m              ^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
[36mcelery-beat_1  |[0m     sys.exit(_main())
[36mcelery-beat_1  |[0m              ^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
[36mcelery-beat_1  |[0m     return celery(auto_envvar_prefix="CELERY")
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
[36mcelery-beat_1  |[0m     return self.main(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1363, in main
[36mcelery-beat_1  |[0m     rv = self.invoke(ctx)
[36mcelery-beat_1  |[0m          ^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
[36mcelery-beat_1  |[0m     return _process_result(sub_ctx.command.invoke(sub_ctx))
[36mcelery-beat_1  |[0m                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
[36mcelery-beat_1  |[0m     return ctx.invoke(self.callback, **ctx.params)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
[36mcelery-beat_1  |[0m     return callback(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
[36mcelery-beat_1  |[0m     return f(get_current_context(), *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
[36mcelery-beat_1  |[0m     return f(ctx, *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/beat.py", line 72, in beat
[36mcelery-beat_1  |[0m     return beat().run()
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 82, in run
[36mcelery-beat_1  |[0m     self.init_loader()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 132, in init_loader
[36mcelery-beat_1  |[0m     self.app.loader.init_worker()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 110, in init_worker
[36mcelery-beat_1  |[0m     self.import_default_modules()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 104, in import_default_modules
[36mcelery-beat_1  |[0m     raise response
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m celery beat v5.3.6 (emerald-rush) is starting.
[36mcelery-beat_1  |[0m ERROR 2025-07-28 20:13:00,240 signal 1 125475876522880 Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x721e9ecc5410>> raised: AttributeError("'tuple' object has no attribute 'append'")
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/bin/celery", line 8, in <module>
[36mcelery-beat_1  |[0m     sys.exit(main())
[36mcelery-beat_1  |[0m              ^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
[36mcelery-beat_1  |[0m     sys.exit(_main())
[36mcelery-beat_1  |[0m              ^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
[36mcelery-beat_1  |[0m     return celery(auto_envvar_prefix="CELERY")
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
[36mcelery-beat_1  |[0m     return self.main(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1363, in main
[36mcelery-beat_1  |[0m     rv = self.invoke(ctx)
[36mcelery-beat_1  |[0m          ^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
[36mcelery-beat_1  |[0m     return _process_result(sub_ctx.command.invoke(sub_ctx))
[36mcelery-beat_1  |[0m                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
[36mcelery-beat_1  |[0m     return ctx.invoke(self.callback, **ctx.params)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
[36mcelery-beat_1  |[0m     return callback(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
[36mcelery-beat_1  |[0m     return f(get_current_context(), *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
[36mcelery-beat_1  |[0m     return f(ctx, *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/beat.py", line 72, in beat
[36mcelery-beat_1  |[0m     return beat().run()
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 82, in run
[36mcelery-beat_1  |[0m     self.init_loader()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 132, in init_loader
[36mcelery-beat_1  |[0m     self.app.loader.init_worker()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 110, in init_worker
[36mcelery-beat_1  |[0m     self.import_default_modules()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 104, in import_default_modules
[36mcelery-beat_1  |[0m     raise response
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m celery beat v5.3.6 (emerald-rush) is starting.
[36mcelery-beat_1  |[0m ERROR 2025-07-28 20:13:09,305 signal 1 132584497580928 Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7895b9a19590>> raised: AttributeError("'tuple' object has no attribute 'append'")
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/bin/celery", line 8, in <module>
[36mcelery-beat_1  |[0m     sys.exit(main())
[36mcelery-beat_1  |[0m              ^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
[36mcelery-beat_1  |[0m     sys.exit(_main())
[36mcelery-beat_1  |[0m              ^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
[36mcelery-beat_1  |[0m     return celery(auto_envvar_prefix="CELERY")
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
[36mcelery-beat_1  |[0m     return self.main(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1363, in main
[36mcelery-beat_1  |[0m     rv = self.invoke(ctx)
[36mcelery-beat_1  |[0m          ^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
[36mcelery-beat_1  |[0m     return _process_result(sub_ctx.command.invoke(sub_ctx))
[36mcelery-beat_1  |[0m                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
[36mcelery-beat_1  |[0m     return ctx.invoke(self.callback, **ctx.params)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
[36mcelery-beat_1  |[0m     return callback(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
[36mcelery-beat_1  |[0m     return f(get_current_context(), *args, **kwargs)
[36;1mweb_1          |[0m INFO 2025-07-28 20:12:49,311 cli 1 124438779177856 Starting server at tcp:port=8000:interface=0.0.0.0
[36;1mweb_1          |[0m INFO 2025-07-28 20:12:49,312 server 1 124438779177856 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
[36;1mweb_1          |[0m INFO 2025-07-28 20:12:49,312 server 1 124438779177856 Configuring endpoint tcp:port=8000:interface=0.0.0.0
[36;1mweb_1          |[0m INFO 2025-07-28 20:12:49,313 server 1 124438779177856 Listening on TCP address 0.0.0.0:8000
[36;1mweb_1          |[0m 127.0.0.1:40768 - - [28/Jul/2025:20:12:53] "GET /health/" 200 272
[36;1mweb_1          |[0m 127.0.0.1:52936 - - [28/Jul/2025:20:13:24] "GET /health/" 200 272
[33mcelery_1       |[0m /home/appuser/.local/lib/python3.11/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
[33mcelery_1       |[0m absolutely not recommended!
[33mcelery_1       |[0m 
[33mcelery_1       |[0m Please specify a different user using the --uid option.
[33mcelery_1       |[0m 
[33mcelery_1       |[0m User information: uid=0 euid=0 gid=0 egid=0
[33mcelery_1       |[0m 
[33mcelery_1       |[0m   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[33mcelery_1       |[0m  
[33mcelery_1       |[0m  -------------- celery@93cbc574e8f4 v5.3.6 (emerald-rush)
[33mcelery_1       |[0m --- ***** ----- 
[33mcelery_1       |[0m -- ******* ---- Linux-6.14.0-23-generic-x86_64-with-glibc2.36 2025-07-28 20:12:52
[33mcelery_1       |[0m - *** --- * --- 
[33mcelery_1       |[0m - ** ---------- [config]
[33mcelery_1       |[0m - ** ---------- .> app:         gymapp:0x79223da53610
[33mcelery_1       |[0m - ** ---------- .> transport:   redis://redis:6379/0
[33mcelery_1       |[0m - ** ---------- .> results:     redis://redis:6379/0
[33mcelery_1       |[0m - *** --- * --- .> concurrency: 2 (prefork)
[33mcelery_1       |[0m -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
[33mcelery_1       |[0m --- ***** ----- 
[33mcelery_1       |[0m  -------------- [queues]
[33mcelery_1       |[0m                 .> celery           exchange=celery(direct) key=celery
[33mcelery_1       |[0m                 
[33mcelery_1       |[0m 
[33mcelery_1       |[0m [tasks]
[33mcelery_1       |[0m   . gymapp.celery.debug_task
[33mcelery_1       |[0m   . invoices.tasks.cleanup_old_invoices
[33mcelery_1       |[0m   . invoices.tasks.generate_daily_invoices
[33mcelery_1       |[0m   . invoices.tasks.generate_invoice_for_member
[33mcelery_1       |[0m   . invoices.tasks.process_overdue_invoices
[33mcelery_1       |[0m   . reports.tasks.cleanup_old_reports
[33mcelery_1       |[0m   . reports.tasks.generate_daily_summary_report
[33mcelery_1       |[0m   . reports.tasks.generate_report
[33mcelery_1       |[0m 
[33mcelery_1       |[0m [2025-07-28 20:12:53,405: WARNING/MainProcess] /home/appuser/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
[33mcelery_1       |[0m whether broker connection retries are made during startup in Celery 6.0 and above.
[33mcelery_1       |[0m If you wish to retain the existing behavior for retrying connections on startup,
[33mcelery_1       |[0m you should set broker_connection_retry_on_startup to True.
[33mcelery_1       |[0m   warnings.warn(
[33mcelery_1       |[0m 
[33mcelery_1       |[0m [2025-07-28 20:12:53,461: WARNING/MainProcess] /home/appuser/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
[33mcelery_1       |[0m whether broker connection retries are made during startup in Celery 6.0 and above.
[33mcelery_1       |[0m If you wish to retain the existing behavior for retrying connections on startup,
[33mcelery_1       |[0m you should set broker_connection_retry_on_startup to True.
[33mcelery_1       |[0m   warnings.warn(
[33mcelery_1       |[0m 
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
[36mcelery-beat_1  |[0m     return f(ctx, *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/beat.py", line 72, in beat
[36mcelery-beat_1  |[0m     return beat().run()
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 82, in run
[36mcelery-beat_1  |[0m     self.init_loader()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 132, in init_loader
[36mcelery-beat_1  |[0m     self.app.loader.init_worker()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 110, in init_worker
[36mcelery-beat_1  |[0m     self.import_default_modules()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 104, in import_default_modules
[36mcelery-beat_1  |[0m     raise response
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m celery beat v5.3.6 (emerald-rush) is starting.
[36mcelery-beat_1  |[0m ERROR 2025-07-28 20:13:18,160 signal 1 134388464245632 Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7a39be6d1890>> raised: AttributeError("'tuple' object has no attribute 'append'")
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m Traceback (most recent call last):
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/bin/celery", line 8, in <module>
[36mcelery-beat_1  |[0m     sys.exit(main())
[36mcelery-beat_1  |[0m              ^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
[36mcelery-beat_1  |[0m     sys.exit(_main())
[36mcelery-beat_1  |[0m              ^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
[36mcelery-beat_1  |[0m     return celery(auto_envvar_prefix="CELERY")
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
[36mcelery-beat_1  |[0m     return self.main(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1363, in main
[36mcelery-beat_1  |[0m     rv = self.invoke(ctx)
[36mcelery-beat_1  |[0m          ^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1830, in invoke
[36mcelery-beat_1  |[0m     return _process_result(sub_ctx.command.invoke(sub_ctx))
[36mcelery-beat_1  |[0m                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
[36mcelery-beat_1  |[0m     return ctx.invoke(self.callback, **ctx.params)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
[36mcelery-beat_1  |[0m     return callback(*args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
[36mcelery-beat_1  |[0m     return f(get_current_context(), *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
[36mcelery-beat_1  |[0m     return f(ctx, *args, **kwargs)
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/bin/beat.py", line 72, in beat
[36mcelery-beat_1  |[0m     return beat().run()
[36mcelery-beat_1  |[0m            ^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 82, in run
[36mcelery-beat_1  |[0m     self.init_loader()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/apps/beat.py", line 132, in init_loader
[36mcelery-beat_1  |[0m     self.app.loader.init_worker()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 110, in init_worker
[36mcelery-beat_1  |[0m     self.import_default_modules()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/loaders/base.py", line 104, in import_default_modules
[36mcelery-beat_1  |[0m     raise response
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
[36mcelery-beat_1  |[0m     response = receiver(signal=self, sender=sender, **named)
[36mcelery-beat_1  |[0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 97, in on_import_modules
[36mcelery-beat_1  |[0m     self.worker_fixup.validate_models()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/celery/fixups/django.py", line 137, in validate_models
[36mcelery-beat_1  |[0m     run_checks()
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
[36mcelery-beat_1  |[0m     new_errors = check(app_configs=app_configs, databases=databases)
[36mcelery-beat_1  |[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 89, in check_django_csp_lt_4_0
[36mcelery-beat_1  |[0m     config, REPORT_ONLY = migrate_settings()
[36mcelery-beat_1  |[0m                           ^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m   File "/home/appuser/.local/lib/python3.11/site-packages/csp/checks.py", line 79, in migrate_settings
[36mcelery-beat_1  |[0m     config["DIRECTIVES"][directive].append(NONCE)
[36mcelery-beat_1  |[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mcelery-beat_1  |[0m AttributeError: 'tuple' object has no attribute 'append'
[36mcelery-beat_1  |[0m celery beat v5.3.6 (emerald-rush) is starting.
